name: Automatic download of METAR from NOAA

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Propojeni s repozitarem
      uses: actions/checkout@v2
    - name: Stahni METAR zpravu z NOAA
      run: |-
        wget -q -O prague.txt https://tgftp.nws.noaa.gov/data/observations/metar/stations/LKPR.TXT
    - name: Save message to git
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Posledni data: ${timestamp}" || exit 0
        git push
